<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>regression</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>22ea5748-3757-4983-8db4-75cee4168ef5</testSuiteGuid>
   <testCaseLink>
      <guid>e021a7d9-fad4-4f60-ad03-abc93bf179ae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>dd267730-7204-4d63-ad0b-726a32668f3d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0ee0b9d-a5d2-41a4-aa7c-dcf89ba8f5d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>dd267730-7204-4d63-ad0b-726a32668f3d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>ced2630d-8872-40f7-b215-db47cda0be58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>dd267730-7204-4d63-ad0b-726a32668f3d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>dbed5358-8ae6-43ca-a0fa-c8aa44d603d3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>749767df-11ad-456d-8086-54578d77e0fa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/searchArticleValid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b16ac82f-3586-4289-9896-ff42469933cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>551e4c80-c204-4157-b920-5bc0fcbdb8e9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
