<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Region</name>
   <tag></tag>
   <elementGuidId>cd5d972f-e634-41d1-a9b5-244feae0f249</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='input-payment-zone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-payment-zone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d940cf43-0867-4979-96a5-ed095d6fb8ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zone_id</value>
      <webElementGuid>9738e193-8257-40dc-9cfd-a9ee8b2edff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-payment-zone</value>
      <webElementGuid>bdea2d21-7abd-468e-b335-b19b11f11909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>302b0b99-bc34-4157-a20c-80cea8426efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> --- Please Select --- AberdeenAberdeenshireAngleseyAngusArgyll and ButeBedfordshireBerkshireBlaenau GwentBridgendBristolBuckinghamshireCaerphillyCambridgeshireCardiffCarmarthenshireCeredigionCheshireClackmannanshireConwyCornwallCounty AntrimCounty ArmaghCounty DownCounty FermanaghCounty LondonderryCounty TyroneCumbriaDenbighshireDerbyshireDevonDorsetDumfries and GallowayDundeeDurhamEast AyrshireEast DunbartonshireEast LothianEast RenfrewshireEast Riding of YorkshireEast SussexEdinburghEssexFalkirkFifeFlintshireGlasgowGloucestershireGreater LondonGreater ManchesterGwyneddHampshireHerefordshireHertfordshireHighlandsInverclydeIsle of WightKentLancashireLeicestershireLincolnshireMerseysideMerthyr TydfilMidlothianMonmouthshireMorayNeath Port TalbotNewportNorfolkNorth AyrshireNorth LanarkshireNorth YorkshireNorthamptonshireNorthumberlandNottinghamshireOrkney IslandsOxfordshirePembrokeshirePerth and KinrossPowysRenfrewshireRhondda Cynon TaffRutlandScottish BordersShetland IslandsShropshireSomersetSouth AyrshireSouth LanarkshireSouth YorkshireStaffordshireStirlingSuffolkSurreySwanseaTorfaenTyne and WearVale of GlamorganWarwickshireWest DunbartonshireWest LothianWest MidlandsWest SussexWest YorkshireWestern IslesWiltshireWorcestershireWrexham</value>
      <webElementGuid>9d98bcb1-f517-43fd-a112-626b04424610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-payment-zone&quot;)</value>
      <webElementGuid>ac65589c-a666-488f-bec4-33bad856a8d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='input-payment-zone']</value>
      <webElementGuid>543bf2ca-d6b1-40ba-ab0e-0e5d7534a503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-new']/div[9]/div/select</value>
      <webElementGuid>4861292a-e3be-4aa1-be4f-4801f669937b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Region / State'])[1]/following::select[1]</value>
      <webElementGuid>362aa08a-3f75-4369-b321-91faac74435d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/following::select[2]</value>
      <webElementGuid>c40c94a6-f813-434e-a918-f3861420f991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Step 3: Delivery Details'])[1]/preceding::select[1]</value>
      <webElementGuid>b7ea2035-a020-43bb-a114-87b2594ac03b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Step 4: Delivery Method'])[1]/preceding::select[1]</value>
      <webElementGuid>edcbdf54-9f99-4fd0-8db1-a01e05c78533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/select</value>
      <webElementGuid>e7d82b7a-4ca9-41e9-a73e-983c7d60d475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'zone_id' and @id = 'input-payment-zone' and (text() = ' --- Please Select --- AberdeenAberdeenshireAngleseyAngusArgyll and ButeBedfordshireBerkshireBlaenau GwentBridgendBristolBuckinghamshireCaerphillyCambridgeshireCardiffCarmarthenshireCeredigionCheshireClackmannanshireConwyCornwallCounty AntrimCounty ArmaghCounty DownCounty FermanaghCounty LondonderryCounty TyroneCumbriaDenbighshireDerbyshireDevonDorsetDumfries and GallowayDundeeDurhamEast AyrshireEast DunbartonshireEast LothianEast RenfrewshireEast Riding of YorkshireEast SussexEdinburghEssexFalkirkFifeFlintshireGlasgowGloucestershireGreater LondonGreater ManchesterGwyneddHampshireHerefordshireHertfordshireHighlandsInverclydeIsle of WightKentLancashireLeicestershireLincolnshireMerseysideMerthyr TydfilMidlothianMonmouthshireMorayNeath Port TalbotNewportNorfolkNorth AyrshireNorth LanarkshireNorth YorkshireNorthamptonshireNorthumberlandNottinghamshireOrkney IslandsOxfordshirePembrokeshirePerth and KinrossPowysRenfrewshireRhondda Cynon TaffRutlandScottish BordersShetland IslandsShropshireSomersetSouth AyrshireSouth LanarkshireSouth YorkshireStaffordshireStirlingSuffolkSurreySwanseaTorfaenTyne and WearVale of GlamorganWarwickshireWest DunbartonshireWest LothianWest MidlandsWest SussexWest YorkshireWestern IslesWiltshireWorcestershireWrexham' or . = ' --- Please Select --- AberdeenAberdeenshireAngleseyAngusArgyll and ButeBedfordshireBerkshireBlaenau GwentBridgendBristolBuckinghamshireCaerphillyCambridgeshireCardiffCarmarthenshireCeredigionCheshireClackmannanshireConwyCornwallCounty AntrimCounty ArmaghCounty DownCounty FermanaghCounty LondonderryCounty TyroneCumbriaDenbighshireDerbyshireDevonDorsetDumfries and GallowayDundeeDurhamEast AyrshireEast DunbartonshireEast LothianEast RenfrewshireEast Riding of YorkshireEast SussexEdinburghEssexFalkirkFifeFlintshireGlasgowGloucestershireGreater LondonGreater ManchesterGwyneddHampshireHerefordshireHertfordshireHighlandsInverclydeIsle of WightKentLancashireLeicestershireLincolnshireMerseysideMerthyr TydfilMidlothianMonmouthshireMorayNeath Port TalbotNewportNorfolkNorth AyrshireNorth LanarkshireNorth YorkshireNorthamptonshireNorthumberlandNottinghamshireOrkney IslandsOxfordshirePembrokeshirePerth and KinrossPowysRenfrewshireRhondda Cynon TaffRutlandScottish BordersShetland IslandsShropshireSomersetSouth AyrshireSouth LanarkshireSouth YorkshireStaffordshireStirlingSuffolkSurreySwanseaTorfaenTyne and WearVale of GlamorganWarwickshireWest DunbartonshireWest LothianWest MidlandsWest SussexWest YorkshireWestern IslesWiltshireWorcestershireWrexham')]</value>
      <webElementGuid>e63da8af-dacf-4f9f-b99b-d89ec07b2b17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
